### ISSUE TITLE
Options headings are too small

### ISSUE THREAD

**Issue by wilzbach** [microservices/openmicroservices.org#154]
![image](https://user-images.githubusercontent.com/4370550/67273162-357f2780-f4be-11e9-9a39-70f9ce949f35.png)

**Comment by matthewhudson** [comment]
I've re-written that portion of the CLI documentation, and we're looking much better now:

<img width="774" alt="Screen Shot 2019-11-18 at 2 08 46 PM" src="https://user-images.githubusercontent.com/320194/69081890-f1276e80-0a0c-11ea-8a29-4b34d71771c6.png">
