### ISSUE TITLE
Add OpenGraph and Twitter Card metadata

### ISSUE THREAD

**Issue by lucperkins** [microservices/openmicroservices.org#192]
I just tweeted about this project and it became clear that the site doesn't specify OpenGraph or Twitter Card metadata. Would be nice to have this, so that my next tweet about it pulls up a nice logo and site description 😀

**Comment by JeanBarriere** [comment]
Hi @lucperkins !

Thank you for your interest. I'm moving to that right now so that you can share and spread the word more easily :)

Cheers !

**Comment by matthewhudson** [comment]
@all-contributors please @lucperkins for ideas

**Comment by matthewhudson** [comment]
@all-contributors please add @lucperkins for ideas
