### ISSUE TITLE
Possibility of introducing async action types

### ISSUE THREAD

**Issue by ig0rsky** [microservices/openmicroservices.org#194]
Are there any plans for introducing more pub/sub protocols into possible actions/event? 
For reference, something like this: https://github.com/asyncapi/asyncapi

Would be great to have async protocols + REST API's covered under the same spec. 

Implementing MQTT actions would be a good first-choice.

**Comment by matthewhudson** [comment]
Hi @ig0rsky! 

Thanks for reaching out - and yes, we agree that adding more transport protocols is essential.

At the moment, we're using real-life use-cases and examples to help drive specification development. Do you have any use-cases in mind?
