### ISSUE TITLE
Fix Google Analytics implementation

### ISSUE THREAD

**Issue by matthewhudson** [microservices/openmicroservices.org#195]
We're using `UA-119018759-1` as our GA id, but I'm not clear which Google Analytics account that data is sent. It doesn't seem to appear in the main Storyscript GA account.

I want to first try (a) to track down where that data currently exists, or alternatively (b) create a new Google Analytics tracker id within the main Storyscript GA account.

CC @stevepeak @judepereira in case either of you know more.

**Comment by stevepeak** [comment]
`UA-119018759-1` is one of our properties. I can invite you into it 👍
